name: Hanszen College

#categories: ['about', 'calendar', 'contact', 'forms', 'government', 'oweek', 'resources']
category-list: [about, government, o-week, resources, forms, calendar, contact]

gems:
  - jekyll-redirect-from #https://github.com/jekyll/jekyll-redirect-from